// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

package ext4image

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/tencentcloud/CubeSandbox/Cubelet/pkg/constants"
	"github.com/tencentcloud/CubeSandbox/Cubelet/pkg/container/pmem"
	cubeimages "github.com/tencentcloud/CubeSandbox/pkgs/proto/services/images/v1"
)

func initTestPmemPaths(t *testing.T, baseDir string) {
	t.Helper()
	paths, err := pmem.ResolvePaths(baseDir, "", "")
	if err != nil {
		t.Fatal(err)
	}
	previous := pmem.CurrentPaths()
	pmem.InitPaths(paths)
	t.Cleanup(func() { pmem.InitPaths(previous) })
}

func writeTestFile(t *testing.T, path string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll %s error=%v", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("WriteFile %s error=%v", path, err)
	}
}

func writeSharedKernelFile(t *testing.T, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetSharedKernelFilePath(), content)
}

func writeRawImageFile(t *testing.T, instanceType, imageRef string, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetRawImageFilePath(instanceType, imageRef), content)
}

func writeRawKernelFile(t *testing.T, instanceType, imageRef string, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetRawKernelFilePath(instanceType, imageRef), content)
}

func TestRefreshArtifactRuntimeFilesRefreshesKernelWhenSharedKernelChanges(t *testing.T) {
	baseDir := t.TempDir()
	paths, pathErr := pmem.ResolvePaths(baseDir, filepath.Join(t.TempDir(), "artifacts"), filepath.Join(t.TempDir(), "vmlinux"))
	if pathErr != nil {
		t.Fatal(pathErr)
	}
	previous := pmem.CurrentPaths()
	pmem.InitPaths(paths)
	t.Cleanup(func() { pmem.InitPaths(previous) })

	kernelV1 := bytes.Repeat([]byte("a"), 2048)
	writeSharedKernelFile(t, kernelV1)

	if err := RefreshArtifactRuntimeFiles(context.Background(), "cubebox", "artifact-1"); err != nil {
		t.Fatalf("RefreshArtifactRuntimeFiles error=%v", err)
	}

	targetKernelPath := pmem.GetRawKernelFilePath("cubebox", "artifact-1")
	got, err := os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel error=%v", err)
	}
	if !bytes.Equal(got, kernelV1) {
		t.Fatal("target kernel content mismatch after first copy")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-1", kernelV1)

	kernelV2 := bytes.Repeat([]byte("b"), 4096)
	writeSharedKernelFile(t, kernelV2)
	if err := RefreshArtifactRuntimeFiles(context.Background(), "cubebox", "artifact-1"); err != nil {
		t.Fatalf("RefreshArtifactRuntimeFiles second call error=%v", err)
	}

	got, err = os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel after second call error=%v", err)
	}
	if !bytes.Equal(got, kernelV2) {
		t.Fatal("target kernel should refresh to latest shared content")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-1", kernelV2)
}

func TestEnsurePmemFilePreservesExistingRuntimeFiles(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	writeSharedKernelFile(t, bytes.Repeat([]byte("s"), 3072))
	writeRawImageFile(t, "cubebox", "artifact-2", bytes.Repeat([]byte("e"), 2048))
	targetKernelPath := pmem.GetRawKernelFilePath("cubebox", "artifact-2")
	oldKernel := bytes.Repeat([]byte("o"), 3072)
	writeRawKernelFile(t, "cubebox", "artifact-2", oldKernel)
	ctx := constants.WithImageSpec(context.Background(), &cubeimages.ImageSpec{
		Annotations: map[string]string{
			constants.MasterAnnotationRootfsArtifactURL:    "http://unused.example/artifact.ext4",
			constants.MasterAnnotationRootfsArtifactSHA256: "deadbeef",
		},
	})

	if err := EnsurePmemFile(ctx, "cubebox", "artifact-2"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel error=%v", err)
	}
	if !bytes.Equal(got, oldKernel) {
		t.Fatal("target kernel should stay unchanged when file already exists")
	}
	if _, statErr := os.Stat(rawKernelVersionPath("cubebox", "artifact-2")); !os.IsNotExist(statErr) {
		t.Fatalf("existing runtime version should not be required or generated by EnsurePmemFile, statErr=%v", statErr)
	}
}

func TestEnsurePmemFileMaterializesFreshArtifactKernel(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	sharedKernel := bytes.Repeat([]byte("s"), 3072)
	writeSharedKernelFile(t, sharedKernel)
	writeRawImageFile(t, "cubebox", "artifact-3", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemFile(context.Background(), "cubebox", "artifact-3"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(pmem.GetRawKernelFilePath("cubebox", "artifact-3"))
	if err != nil {
		t.Fatalf("ReadFile materialized kernel error=%v", err)
	}
	if !bytes.Equal(got, sharedKernel) {
		t.Fatal("materialized kernel should match shared kernel")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-3", sharedKernel)
}

func TestEnsurePmemRootfsDoesNotRequireKernelFile(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	writeRawImageFile(t, "cubebox", "artifact-4", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemRootfs(context.Background(), "cubebox", "artifact-4"); err != nil {
		t.Fatalf("EnsurePmemRootfs error=%v", err)
	}
}

func TestEnsurePmemFileDoesNotRequireCubeImageVersionFile(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	sharedKernel := bytes.Repeat([]byte("s"), 3072)
	writeSharedKernelFile(t, sharedKernel)
	writeRawImageFile(t, "cubebox", "artifact-5", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemFile(context.Background(), "cubebox", "artifact-5"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(pmem.GetRawKernelFilePath("cubebox", "artifact-5"))
	if err != nil {
		t.Fatalf("ReadFile materialized kernel error=%v", err)
	}
	if !bytes.Equal(got, sharedKernel) {
		t.Fatal("materialized kernel should match shared kernel")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-5", sharedKernel)
}

func TestEnsureKernelFilePresentRequiresSharedKernel(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	err := ensureKernelFilePresent(context.Background(), "cubebox", "artifact-2")
	if err == nil {
		t.Fatal("ensureKernelFilePresent error=nil, want non-nil")
	}
}

func rawKernelVersionPath(instanceType, imageRef string) string {
	return filepath.Join(filepath.Dir(pmem.GetRawKernelFilePath(instanceType, imageRef)), "version")
}

func kernelVersionForContent(content []byte) string {
	sum := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func assertRawKernelVersionMatches(t *testing.T, instanceType, imageRef string, kernel []byte) {
	t.Helper()
	got, err := os.ReadFile(rawKernelVersionPath(instanceType, imageRef))
	if err != nil {
		t.Fatalf("ReadFile kernel version error=%v", err)
	}
	if strings.TrimSpace(string(got)) != kernelVersionForContent(kernel) {
		t.Fatalf("kernel version=%q, want %q", strings.TrimSpace(string(got)), kernelVersionForContent(kernel))
	}
}

func TestDestroyPmemArtifactResolvesSymlinkedBase(t *testing.T) {
	dataDir := t.TempDir()
	realBase := filepath.Join(t.TempDir(), "cubebox_os_image")
	if err := os.MkdirAll(realBase, 0o755); err != nil {
		t.Fatalf("MkdirAll real base error=%v", err)
	}
	if err := os.Symlink(realBase, filepath.Join(dataDir, "cubebox_os_image")); err != nil {
		t.Fatalf("Symlink base error=%v", err)
	}
	initTestPmemPaths(t, dataDir)

	artifactDir := filepath.Join(realBase, "artifact-6")
	writeTestFile(t, filepath.Join(artifactDir, "artifact-6.ext4"), []byte("rootfs"))

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-6", nil); err != nil {
		t.Fatalf("DestroyPmemArtifact error=%v", err)
	}
	if _, err := os.Stat(artifactDir); !os.IsNotExist(err) {
		t.Fatalf("artifact dir should be removed, stat err=%v", err)
	}
}

func TestDestroyPmemArtifactUnlinksLeafSymlinkOnly(t *testing.T) {
	dataDir := t.TempDir()
	initTestPmemPaths(t, dataDir)
	base := pmem.GetPmemBasePath("cubebox")
	if err := os.MkdirAll(base, 0o755); err != nil {
		t.Fatalf("MkdirAll base error=%v", err)
	}
	outside := t.TempDir()
	outsideFile := filepath.Join(outside, "keep.txt")
	if err := os.WriteFile(outsideFile, []byte("keep"), 0o644); err != nil {
		t.Fatalf("WriteFile outside error=%v", err)
	}
	leaf := filepath.Join(base, "artifact-7")
	if err := os.Symlink(outside, leaf); err != nil {
		t.Fatalf("Symlink leaf error=%v", err)
	}

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-7", nil); err != nil {
		t.Fatalf("DestroyPmemArtifact error=%v", err)
	}
	if _, err := os.Lstat(leaf); !os.IsNotExist(err) {
		t.Fatalf("artifact symlink should be removed, lstat err=%v", err)
	}
	if _, err := os.Stat(outsideFile); err != nil {
		t.Fatalf("outside target should remain, stat err=%v", err)
	}
}

func TestDestroyPmemArtifactMissingBaseIsIdempotent(t *testing.T) {
	dataDir := t.TempDir()
	initTestPmemPaths(t, dataDir)

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-8", nil); err != nil {
		t.Fatalf("missing pmem base should be success, got %v", err)
	}
}

func TestDownloadArtifactWithIndependentKernelSource(t *testing.T) {
	paths, err := pmem.ResolvePaths(t.TempDir(), filepath.Join(t.TempDir(), "images"), filepath.Join(t.TempDir(), "vmlinux"))
	if err != nil {
		t.Fatal(err)
	}
	previous := pmem.CurrentPaths()
	pmem.InitPaths(paths)
	t.Cleanup(func() { pmem.InitPaths(previous) })
	rootfs := bytes.Repeat([]byte("r"), 2048)
	kernel := bytes.Repeat([]byte("k"), 2048)
	writeSharedKernelFile(t, kernel)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { _, _ = w.Write(rootfs) }))
	defer server.Close()
	sum := sha256.Sum256(rootfs)
	ctx := constants.WithImageSpec(context.Background(), &cubeimages.ImageSpec{Annotations: map[string]string{
		constants.MasterAnnotationRootfsArtifactURL:    server.URL,
		constants.MasterAnnotationRootfsArtifactSHA256: hex.EncodeToString(sum[:]),
	}})
	if err := EnsurePmemFile(ctx, "cubebox", "rfs-download"); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string][]byte{paths.ImageFile("cubebox", "rfs-download"): rootfs, paths.KernelFile("cubebox", "rfs-download"): kernel} {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("artifact %s: err=%v, content matches=%v", path, err, bytes.Equal(got, want))
		}
	}
	if err := DestroyPmemArtifact(ctx, "cubebox", "rfs-download", nil); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(paths.ImageFile("cubebox", "rfs-download")); !os.IsNotExist(err) {
		t.Fatalf("artifact was not deleted: %v", err)
	}
	if _, err := os.Stat(paths.SharedKernelPath); err != nil {
		t.Fatalf("shared kernel must survive artifact deletion: %v", err)
	}
}

func TestEnsurePmemRootfsMixedEntrypointsReusePreparedFile(t *testing.T) {
	baseDir := t.TempDir()
	initTestPmemPaths(t, baseDir)

	rootfs := bytes.Repeat([]byte("concurrent-rootfs"), 256)
	kernel := bytes.Repeat([]byte("concurrent-kernel"), 256)
	writeSharedKernelFile(t, kernel)
	var requests atomic.Int32
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		requests.Add(1)
		time.Sleep(25 * time.Millisecond)
		_, _ = w.Write(rootfs)
	}))
	defer server.Close()

	sum := sha256.Sum256(rootfs)
	ctx := constants.WithImageSpec(context.Background(), &cubeimages.ImageSpec{Annotations: map[string]string{
		constants.MasterAnnotationRootfsArtifactURL:    server.URL,
		constants.MasterAnnotationRootfsArtifactSHA256: hex.EncodeToString(sum[:]),
	}})

	const concurrency = 8
	start := make(chan struct{})
	errs := make(chan error, concurrency)
	var wg sync.WaitGroup
	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func(useRootfsEntrypoint bool) {
			defer wg.Done()
			<-start
			if useRootfsEntrypoint {
				errs <- EnsurePmemRootfs(ctx, "cubebox", "rfs-concurrent")
				return
			}
			errs <- EnsurePmemFile(ctx, "cubebox", "rfs-concurrent")
		}(i%2 == 0)
	}
	close(start)
	wg.Wait()
	close(errs)

	for err := range errs {
		if err != nil {
			t.Fatalf("ensure pmem file error = %v", err)
		}
	}
	if got := requests.Load(); got != 1 {
		t.Fatalf("download requests = %d, want 1", got)
	}
	if got, err := os.ReadFile(pmem.GetRawImageFilePath("cubebox", "rfs-concurrent")); err != nil || !bytes.Equal(got, rootfs) {
		t.Fatalf("prepared rootfs mismatch: err=%v", err)
	}
	if got, err := os.ReadFile(pmem.GetRawKernelFilePath("cubebox", "rfs-concurrent")); err != nil || !bytes.Equal(got, kernel) {
		t.Fatalf("prepared kernel mismatch: err=%v", err)
	}
}
