# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Tencent. All rights reserved.
#
# Build-context filter for CubeMaster/docker/Dockerfile.cubemastercli
# (context = repository root). Allow the trees this Dockerfile COPYs;
# no deploy/scripts (CLI image has no volume-deps installer).
**
!CubeMaster
!CubeMaster/**
!pkgs
!pkgs/CubeLog
!pkgs/CubeLog/**
!pkgs/blobstore
!pkgs/blobstore/**
!pkgs/cubedb
!pkgs/cubedb/**
!pkgs/proto
!pkgs/proto/**
!Cubelet
!Cubelet/**
!CubeOps
!CubeOps/**
