// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/cubehost/v1/hostimage.proto

package cubehost

import (
	v1 "github.com/tencentcloud/CubeSandbox/pkgs/proto/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_CLIENT_HELLO          MessageType = 0
	MessageType_IMAGE_FORWARD         MessageType = 1
	MessageType_REMOVE_SNAPSHOT       MessageType = 2
	MessageType_LIST_INFLIGHT_REQUEST MessageType = 3
	MessageType_IMAGE_FS_STATS        MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "CLIENT_HELLO",
		1: "IMAGE_FORWARD",
		2: "REMOVE_SNAPSHOT",
		3: "LIST_INFLIGHT_REQUEST",
		4: "IMAGE_FS_STATS",
	}
	MessageType_value = map[string]int32{
		"CLIENT_HELLO":          0,
		"IMAGE_FORWARD":         1,
		"REMOVE_SNAPSHOT":       2,
		"LIST_INFLIGHT_REQUEST": 3,
		"IMAGE_FS_STATS":        4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_cubehost_v1_hostimage_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_services_cubehost_v1_hostimage_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{0}
}

type ResponseStatusCode int32

const (
	ResponseStatusCode_OK    ResponseStatusCode = 0
	ResponseStatusCode_ERROR ResponseStatusCode = 1
)

// Enum value maps for ResponseStatusCode.
var (
	ResponseStatusCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	ResponseStatusCode_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x ResponseStatusCode) Enum() *ResponseStatusCode {
	p := new(ResponseStatusCode)
	*p = x
	return p
}

func (x ResponseStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_cubehost_v1_hostimage_proto_enumTypes[1].Descriptor()
}

func (ResponseStatusCode) Type() protoreflect.EnumType {
	return &file_api_services_cubehost_v1_hostimage_proto_enumTypes[1]
}

func (x ResponseStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatusCode.Descriptor instead.
func (ResponseStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{1}
}

type LayerType int32

const (
	LayerType_LAYER_TYPE_FS     LayerType = 0
	LayerType_LAYER_TYPE_DEVICE LayerType = 1
)

// Enum value maps for LayerType.
var (
	LayerType_name = map[int32]string{
		0: "LAYER_TYPE_FS",
		1: "LAYER_TYPE_DEVICE",
	}
	LayerType_value = map[string]int32{
		"LAYER_TYPE_FS":     0,
		"LAYER_TYPE_DEVICE": 1,
	}
)

func (x LayerType) Enum() *LayerType {
	p := new(LayerType)
	*p = x
	return p
}

func (x LayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_cubehost_v1_hostimage_proto_enumTypes[2].Descriptor()
}

func (LayerType) Type() protoreflect.EnumType {
	return &file_api_services_cubehost_v1_hostimage_proto_enumTypes[2]
}

func (x LayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerType.Descriptor instead.
func (LayerType) EnumDescriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{2}
}

type ClientMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status *ResponseStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Type   MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=cubelet.services.cubebox.hostimage.v1.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_ForwardImageResponse
	//	*ClientMessage_Common
	//	*ClientMessage_ListInflightRequest
	//	*ClientMessage_ImageFsStats
	Content       isClientMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientMessage) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ClientMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_CLIENT_HELLO
}

func (x *ClientMessage) GetContent() isClientMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ClientMessage) GetHello() string {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return ""
}

func (x *ClientMessage) GetForwardImageResponse() *ForwardImageResponse {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_ForwardImageResponse); ok {
			return x.ForwardImageResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetCommon() string {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_Common); ok {
			return x.Common
		}
	}
	return ""
}

func (x *ClientMessage) GetListInflightRequest() *ListInflightRequest {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_ListInflightRequest); ok {
			return x.ListInflightRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetImageFsStats() *ImageFsStats {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_ImageFsStats); ok {
			return x.ImageFsStats
		}
	}
	return nil
}

type isClientMessage_Content interface {
	isClientMessage_Content()
}

type ClientMessage_Hello struct {
	Hello string `protobuf:"bytes,100,opt,name=hello,proto3,oneof"` // 客户端连接通知
}

type ClientMessage_ForwardImageResponse struct {
	ForwardImageResponse *ForwardImageResponse `protobuf:"bytes,101,opt,name=forwardImageResponse,proto3,oneof"` // 下载操作响应
}

type ClientMessage_Common struct {
	Common string `protobuf:"bytes,102,opt,name=common,proto3,oneof"` // 通用消息
}

type ClientMessage_ListInflightRequest struct {
	ListInflightRequest *ListInflightRequest `protobuf:"bytes,103,opt,name=listInflightRequest,proto3,oneof"` // 列出正在进行的请求
}

type ClientMessage_ImageFsStats struct {
	ImageFsStats *ImageFsStats `protobuf:"bytes,104,opt,name=imageFsStats,proto3,oneof"` // 获取镜像文件系统信息
}

func (*ClientMessage_Hello) isClientMessage_Content() {}

func (*ClientMessage_ForwardImageResponse) isClientMessage_Content() {}

func (*ClientMessage_Common) isClientMessage_Content() {}

func (*ClientMessage_ListInflightRequest) isClientMessage_Content() {}

func (*ClientMessage_ImageFsStats) isClientMessage_Content() {}

type ServerMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status *ResponseStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Type   MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=cubelet.services.cubebox.hostimage.v1.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*ServerMessage_Hello
	//	*ServerMessage_ForwardImageRequest
	//	*ServerMessage_RemoveSnapshotRequest
	//	*ServerMessage_ListInflightRequest
	Content       isServerMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMessage) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_CLIENT_HELLO
}

func (x *ServerMessage) GetContent() isServerMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ServerMessage) GetHello() string {
	if x != nil {
		if x, ok := x.Content.(*ServerMessage_Hello); ok {
			return x.Hello
		}
	}
	return ""
}

func (x *ServerMessage) GetForwardImageRequest() *ForwardImageRequest {
	if x != nil {
		if x, ok := x.Content.(*ServerMessage_ForwardImageRequest); ok {
			return x.ForwardImageRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetRemoveSnapshotRequest() *RemoveSnapshotRequest {
	if x != nil {
		if x, ok := x.Content.(*ServerMessage_RemoveSnapshotRequest); ok {
			return x.RemoveSnapshotRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetListInflightRequest() *ListInflightRequest {
	if x != nil {
		if x, ok := x.Content.(*ServerMessage_ListInflightRequest); ok {
			return x.ListInflightRequest
		}
	}
	return nil
}

type isServerMessage_Content interface {
	isServerMessage_Content()
}

type ServerMessage_Hello struct {
	Hello string `protobuf:"bytes,100,opt,name=hello,proto3,oneof"` // 客户端连接通知
}

type ServerMessage_ForwardImageRequest struct {
	ForwardImageRequest *ForwardImageRequest `protobuf:"bytes,101,opt,name=forwardImageRequest,proto3,oneof"` // 下载操作响应
}

type ServerMessage_RemoveSnapshotRequest struct {
	RemoveSnapshotRequest *RemoveSnapshotRequest `protobuf:"bytes,102,opt,name=removeSnapshotRequest,proto3,oneof"` // 删除快照请求
}

type ServerMessage_ListInflightRequest struct {
	ListInflightRequest *ListInflightRequest `protobuf:"bytes,103,opt,name=listInflightRequest,proto3,oneof"` // 列出正在进行的请求
}

func (*ServerMessage_Hello) isServerMessage_Content() {}

func (*ServerMessage_ForwardImageRequest) isServerMessage_Content() {}

func (*ServerMessage_RemoveSnapshotRequest) isServerMessage_Content() {}

func (*ServerMessage_ListInflightRequest) isServerMessage_Content() {}

type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseStatusCode     `protobuf:"varint,1,opt,name=code,proto3,enum=cubelet.services.cubebox.hostimage.v1.ResponseStatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseStatus) GetCode() ResponseStatusCode {
	if x != nil {
		return x.Code
	}
	return ResponseStatusCode_OK
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForwardImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *HostImage             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardImageResponse) Reset() {
	*x = ForwardImageResponse{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardImageResponse) ProtoMessage() {}

func (x *ForwardImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardImageResponse.ProtoReflect.Descriptor instead.
func (*ForwardImageResponse) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardImageResponse) GetImage() *HostImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type ForwardImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spec of the image.
	Image *v1.ImageSpec `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Authentication configuration for pulling the image.
	Auth *v1.AuthConfig `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	// Config of the PodSandbox, which is used to pull image in PodSandbox context.
	SandboxConfig *PodSandboxConfig `protobuf:"bytes,3,opt,name=sandbox_config,json=sandboxConfig,proto3" json:"sandbox_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardImageRequest) Reset() {
	*x = ForwardImageRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardImageRequest) ProtoMessage() {}

func (x *ForwardImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardImageRequest.ProtoReflect.Descriptor instead.
func (*ForwardImageRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardImageRequest) GetImage() *v1.ImageSpec {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ForwardImageRequest) GetAuth() *v1.AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ForwardImageRequest) GetSandboxConfig() *PodSandboxConfig {
	if x != nil {
		return x.SandboxConfig
	}
	return nil
}

// Basic information about a container image.
type HostImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the image.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Other names by which this image is known.
	RepoTags []string `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	// Digests by which this image is known.
	RepoDigests []string `protobuf:"bytes,3,rep,name=repo_digests,json=repoDigests,proto3" json:"repo_digests,omitempty"`
	// Size of the image in bytes. Must be > 0.
	Size uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// ImageSpec for image which includes annotations
	Spec *v1.ImageSpec `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// all descriptors for this image
	Descriptors []*anypb.Any `protobuf:"bytes,9,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	// LayerMounts is a list of mounts for the image layers.
	LayerMounts []*LayerMount `protobuf:"bytes,10,rep,name=LayerMounts,proto3" json:"LayerMounts,omitempty"`
	// image_devs is list of snapshots belong to erofs image device.
	// A image can consist of the following components:
	// 1. Composed solely of erofs layers
	// 2. The erofs layer serves as the bottom layer, and the regular image
	// layer serves as the upper layer
	// 3. Ordinary image layer
	// That is to say, the image cannot be composed of a regular image layer
	// as the bottom layer and an erofs image layer as the upper layer.
	// And a maximum of one erofs device can be used for one image.
	ImageDevs     *ImageDev `protobuf:"bytes,11,opt,name=image_devs,json=imageDevs,proto3" json:"image_devs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostImage) Reset() {
	*x = HostImage{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostImage) ProtoMessage() {}

func (x *HostImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostImage.ProtoReflect.Descriptor instead.
func (*HostImage) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{5}
}

func (x *HostImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostImage) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *HostImage) GetRepoDigests() []string {
	if x != nil {
		return x.RepoDigests
	}
	return nil
}

func (x *HostImage) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *HostImage) GetSpec() *v1.ImageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *HostImage) GetDescriptors() []*anypb.Any {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *HostImage) GetLayerMounts() []*LayerMount {
	if x != nil {
		return x.LayerMounts
	}
	return nil
}

func (x *HostImage) GetImageDevs() *ImageDev {
	if x != nil {
		return x.ImageDevs
	}
	return nil
}

// Mount specifies a host volume to mount into a container.
type LayerMount struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HostPath string                 `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	VmPath   string                 `protobuf:"bytes,3,opt,name=vm_path,json=vmPath,proto3" json:"vm_path,omitempty"`
	Digest   string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Parent   string                 `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Usage    string                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	// dev_serial_id  is the serial id of the device.
	// this fileds is only used when the mount is a device.like erofs.
	// When a layer belongs to a certain device, it is not allowed
	// to use the `host_path` field again
	DevSerialId   string    `protobuf:"bytes,7,opt,name=dev_serial_id,json=devSerialId,proto3" json:"dev_serial_id,omitempty"`
	LayerType     LayerType `protobuf:"varint,8,opt,name=layer_type,json=layerType,proto3,enum=cubelet.services.cubebox.hostimage.v1.LayerType" json:"layer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerMount) Reset() {
	*x = LayerMount{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerMount) ProtoMessage() {}

func (x *LayerMount) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerMount.ProtoReflect.Descriptor instead.
func (*LayerMount) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{6}
}

func (x *LayerMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayerMount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *LayerMount) GetVmPath() string {
	if x != nil {
		return x.VmPath
	}
	return ""
}

func (x *LayerMount) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *LayerMount) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *LayerMount) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *LayerMount) GetDevSerialId() string {
	if x != nil {
		return x.DevSerialId
	}
	return ""
}

func (x *LayerMount) GetLayerType() LayerType {
	if x != nil {
		return x.LayerType
	}
	return LayerType_LAYER_TYPE_FS
}

type ImageDev struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SerialId       string                 `protobuf:"bytes,1,opt,name=serial_id,json=serialId,proto3" json:"serial_id,omitempty"`
	HostDevicePath string                 `protobuf:"bytes,2,opt,name=host_device_path,json=hostDevicePath,proto3" json:"host_device_path,omitempty"`
	// vm_device_path is the path of the device in the VM.
	// this fileds is only used in the VM.
	VmDevicePath string `protobuf:"bytes,3,opt,name=vm_device_path,json=vmDevicePath,proto3" json:"vm_device_path,omitempty"`
	// this fileds is only used in the VM.
	VmRootPath string `protobuf:"bytes,4,opt,name=vm_root_path,json=vmRootPath,proto3" json:"vm_root_path,omitempty"`
	// fs_type is the filesystem type of the volume.
	FsType       string   `protobuf:"bytes,5,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	MountOptions []string `protobuf:"bytes,6,rep,name=mount_options,json=mountOptions,proto3" json:"mount_options,omitempty"`
	// snapshots is a list of snapshots of the image.
	Snapshots []string `protobuf:"bytes,7,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	// image id of all snapshot
	ImageId         string   `protobuf:"bytes,8,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageReferences []string `protobuf:"bytes,9,rep,name=image_references,json=imageReferences,proto3" json:"image_references,omitempty"`
	// pci bdf of virtio-blk
	Bdf           string `protobuf:"bytes,10,opt,name=bdf,proto3" json:"bdf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDev) Reset() {
	*x = ImageDev{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDev) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDev) ProtoMessage() {}

func (x *ImageDev) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDev.ProtoReflect.Descriptor instead.
func (*ImageDev) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{7}
}

func (x *ImageDev) GetSerialId() string {
	if x != nil {
		return x.SerialId
	}
	return ""
}

func (x *ImageDev) GetHostDevicePath() string {
	if x != nil {
		return x.HostDevicePath
	}
	return ""
}

func (x *ImageDev) GetVmDevicePath() string {
	if x != nil {
		return x.VmDevicePath
	}
	return ""
}

func (x *ImageDev) GetVmRootPath() string {
	if x != nil {
		return x.VmRootPath
	}
	return ""
}

func (x *ImageDev) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *ImageDev) GetMountOptions() []string {
	if x != nil {
		return x.MountOptions
	}
	return nil
}

func (x *ImageDev) GetSnapshots() []string {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ImageDev) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageDev) GetImageReferences() []string {
	if x != nil {
		return x.ImageReferences
	}
	return nil
}

func (x *ImageDev) GetBdf() string {
	if x != nil {
		return x.Bdf
	}
	return ""
}

// PodSandboxMetadata holds all necessary information for building the sandbox name.
// The container runtime is encouraged to expose the metadata associated with the
// PodSandbox in its user interface for better user experience. For example,
// the runtime can construct a unique PodSandboxName based on the metadata.
type PodSandboxMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pod name of the sandbox. Same as the pod name in the Pod ObjectMeta.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Pod UID of the sandbox. Same as the pod UID in the Pod ObjectMeta.
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// Pod namespace of the sandbox. Same as the pod namespace in the Pod ObjectMeta.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Attempt number of creating the sandbox. Default: 0.
	Attempt       uint32 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSandboxMetadata) Reset() {
	*x = PodSandboxMetadata{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSandboxMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSandboxMetadata) ProtoMessage() {}

func (x *PodSandboxMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSandboxMetadata.ProtoReflect.Descriptor instead.
func (*PodSandboxMetadata) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{8}
}

func (x *PodSandboxMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodSandboxMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PodSandboxMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodSandboxMetadata) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// PodSandboxConfig holds all the required and optional fields for creating a
// sandbox.
type PodSandboxConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata of the sandbox. This information will uniquely identify the
	// sandbox, and the runtime should leverage this to ensure correct
	// operation. The runtime may also use this information to improve UX, such
	// as by constructing a readable name.
	Metadata *PodSandboxMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Hostname of the sandbox. Hostname could only be empty when the pod
	// network namespace is NODE.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Path to the directory on the host in which container log files are
	// stored.
	// By default the log of a container going into the LogDirectory will be
	// hooked up to STDOUT and STDERR. However, the LogDirectory may contain
	// binary log files with structured logging data from the individual
	// containers. For example, the files might be newline separated JSON
	// structured logs, systemd-journald journal files, gRPC trace files, etc.
	// E.g.,
	//
	//	PodSandboxConfig.LogDirectory = `/var/log/pods/<NAMESPACE>_<NAME>_<UID>/`
	//	ContainerConfig.LogPath = `containerName/Instance#.log`
	LogDirectory string `protobuf:"bytes,3,opt,name=log_directory,json=logDirectory,proto3" json:"log_directory,omitempty"`
	// DNS config for the sandbox.
	DnsConfig *DNSConfig `protobuf:"bytes,4,opt,name=dns_config,json=dnsConfig,proto3" json:"dns_config,omitempty"`
	// Port mappings for the sandbox.
	// repeated PortMapping port_mappings = 5;
	// Key-value pairs that may be used to scope and select individual resources.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Unstructured key-value map that may be set by the kubelet to store and
	// retrieve arbitrary metadata. This will include any annotations set on a
	// pod through the Kubernetes API.
	//
	// Annotations MUST NOT be altered by the runtime; the annotations stored
	// here MUST be returned in the PodSandboxStatus associated with the pod
	// this PodSandboxConfig creates.
	//
	// In general, in order to preserve a well-defined interface between the
	// kubelet and the container runtime, annotations SHOULD NOT influence
	// runtime behaviour.
	//
	// Annotations can also be useful for runtime authors to experiment with
	// new features that are opaque to the Kubernetes APIs (both user-facing
	// and the CRI). Whenever possible, however, runtime authors SHOULD
	// consider proposing new typed fields for any new features instead.
	Annotations   map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSandboxConfig) Reset() {
	*x = PodSandboxConfig{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSandboxConfig) ProtoMessage() {}

func (x *PodSandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSandboxConfig.ProtoReflect.Descriptor instead.
func (*PodSandboxConfig) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{9}
}

func (x *PodSandboxConfig) GetMetadata() *PodSandboxMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PodSandboxConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PodSandboxConfig) GetLogDirectory() string {
	if x != nil {
		return x.LogDirectory
	}
	return ""
}

func (x *PodSandboxConfig) GetDnsConfig() *DNSConfig {
	if x != nil {
		return x.DnsConfig
	}
	return nil
}

func (x *PodSandboxConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PodSandboxConfig) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// DNSConfig specifies the DNS servers and search domains of a sandbox.
type DNSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of DNS servers of the cluster.
	Servers []string `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// List of DNS search domains of the cluster.
	Searches []string `protobuf:"bytes,2,rep,name=searches,proto3" json:"searches,omitempty"`
	// List of DNS options. See https://linux.die.net/man/5/resolv.conf
	// for all available options.
	Options       []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{10}
}

func (x *DNSConfig) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *DNSConfig) GetSearches() []string {
	if x != nil {
		return x.Searches
	}
	return nil
}

func (x *DNSConfig) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// RemoveSnapshotRequest is the request message for removing a snapshot.
type RemoveSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LayerMounts is a list of mounts for the image layers.
	LayerMounts   []*LayerMount `protobuf:"bytes,10,rep,name=LayerMounts,proto3" json:"LayerMounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSnapshotRequest) Reset() {
	*x = RemoveSnapshotRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSnapshotRequest) ProtoMessage() {}

func (x *RemoveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RemoveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveSnapshotRequest) GetLayerMounts() []*LayerMount {
	if x != nil {
		return x.LayerMounts
	}
	return nil
}

// ListInflightRequest is the request message for listing inflight requests.
type ListInflightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*InflightRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInflightRequest) Reset() {
	*x = ListInflightRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInflightRequest) ProtoMessage() {}

func (x *ListInflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInflightRequest.ProtoReflect.Descriptor instead.
func (*ListInflightRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{12}
}

func (x *ListInflightRequest) GetRequests() []*InflightRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type InflightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InflightRequest) Reset() {
	*x = InflightRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InflightRequest) ProtoMessage() {}

func (x *InflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InflightRequest.ProtoReflect.Descriptor instead.
func (*InflightRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{13}
}

func (x *InflightRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter to list images.
	Filter        *v1.ImageFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{14}
}

func (x *ListImagesRequest) GetFilter() *v1.ImageFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of images.
	Images        []*v1.Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{15}
}

func (x *ListImagesResponse) GetImages() []*v1.Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageFsStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableBytes uint64                 `protobuf:"varint,1,opt,name=AvailableBytes,proto3" json:"AvailableBytes,omitempty"`
	CapacityBytes  uint64                 `protobuf:"varint,2,opt,name=CapacityBytes,proto3" json:"CapacityBytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,3,opt,name=UsedBytes,proto3" json:"UsedBytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageFsStats) Reset() {
	*x = ImageFsStats{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFsStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFsStats) ProtoMessage() {}

func (x *ImageFsStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFsStats.ProtoReflect.Descriptor instead.
func (*ImageFsStats) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{16}
}

func (x *ImageFsStats) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *ImageFsStats) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *ImageFsStats) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type MountImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountImageRequest) Reset() {
	*x = MountImageRequest{}
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountImageRequest) ProtoMessage() {}

func (x *MountImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_cubehost_v1_hostimage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountImageRequest.ProtoReflect.Descriptor instead.
func (*MountImageRequest) Descriptor() ([]byte, []int) {
	return file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP(), []int{17}
}

func (x *MountImageRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *MountImageRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *MountImageRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_api_services_cubehost_v1_hostimage_proto protoreflect.FileDescriptor

const file_api_services_cubehost_v1_hostimage_proto_rawDesc = "" +
	"\n" +
	"(api/services/cubehost/v1/hostimage.proto\x12%cubelet.services.cubebox.hostimage.v1\x1a\x19google/protobuf/any.proto\x1a\x15types/v1/images.proto\"\xb1\x04\n" +
	"\rClientMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12M\n" +
	"\x06status\x18\x02 \x01(\v25.cubelet.services.cubebox.hostimage.v1.ResponseStatusR\x06status\x12F\n" +
	"\x04type\x18\x03 \x01(\x0e22.cubelet.services.cubebox.hostimage.v1.MessageTypeR\x04type\x12\x16\n" +
	"\x05hello\x18d \x01(\tH\x00R\x05hello\x12q\n" +
	"\x14forwardImageResponse\x18e \x01(\v2;.cubelet.services.cubebox.hostimage.v1.ForwardImageResponseH\x00R\x14forwardImageResponse\x12\x18\n" +
	"\x06common\x18f \x01(\tH\x00R\x06common\x12n\n" +
	"\x13listInflightRequest\x18g \x01(\v2:.cubelet.services.cubebox.hostimage.v1.ListInflightRequestH\x00R\x13listInflightRequest\x12Y\n" +
	"\fimageFsStats\x18h \x01(\v23.cubelet.services.cubebox.hostimage.v1.ImageFsStatsH\x00R\fimageFsStatsB\t\n" +
	"\acontent\"\xaf\x04\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12M\n" +
	"\x06status\x18\x02 \x01(\v25.cubelet.services.cubebox.hostimage.v1.ResponseStatusR\x06status\x12F\n" +
	"\x04type\x18\x03 \x01(\x0e22.cubelet.services.cubebox.hostimage.v1.MessageTypeR\x04type\x12\x16\n" +
	"\x05hello\x18d \x01(\tH\x00R\x05hello\x12n\n" +
	"\x13forwardImageRequest\x18e \x01(\v2:.cubelet.services.cubebox.hostimage.v1.ForwardImageRequestH\x00R\x13forwardImageRequest\x12t\n" +
	"\x15removeSnapshotRequest\x18f \x01(\v2<.cubelet.services.cubebox.hostimage.v1.RemoveSnapshotRequestH\x00R\x15removeSnapshotRequest\x12n\n" +
	"\x13listInflightRequest\x18g \x01(\v2:.cubelet.services.cubebox.hostimage.v1.ListInflightRequestH\x00R\x13listInflightRequestB\t\n" +
	"\acontent\"y\n" +
	"\x0eResponseStatus\x12M\n" +
	"\x04code\x18\x01 \x01(\x0e29.cubelet.services.cubebox.hostimage.v1.ResponseStatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\x14ForwardImageResponse\x12F\n" +
	"\x05image\x18\x01 \x01(\v20.cubelet.services.cubebox.hostimage.v1.HostImageR\x05image\"\xd4\x01\n" +
	"\x13ForwardImageRequest\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.cubelet.types.ImageSpecR\x05image\x12-\n" +
	"\x04auth\x18\x02 \x01(\v2\x19.cubelet.types.AuthConfigR\x04auth\x12^\n" +
	"\x0esandbox_config\x18\x03 \x01(\v27.cubelet.services.cubebox.hostimage.v1.PodSandboxConfigR\rsandboxConfig\"\xfa\x02\n" +
	"\tHostImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12!\n" +
	"\frepo_digests\x18\x03 \x03(\tR\vrepoDigests\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12,\n" +
	"\x04spec\x18\a \x01(\v2\x18.cubelet.types.ImageSpecR\x04spec\x126\n" +
	"\vdescriptors\x18\t \x03(\v2\x14.google.protobuf.AnyR\vdescriptors\x12S\n" +
	"\vLayerMounts\x18\n" +
	" \x03(\v21.cubelet.services.cubebox.hostimage.v1.LayerMountR\vLayerMounts\x12N\n" +
	"\n" +
	"image_devs\x18\v \x01(\v2/.cubelet.services.cubebox.hostimage.v1.ImageDevR\timageDevs\"\x91\x02\n" +
	"\n" +
	"LayerMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12\x17\n" +
	"\avm_path\x18\x03 \x01(\tR\x06vmPath\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x16\n" +
	"\x06parent\x18\x05 \x01(\tR\x06parent\x12\x14\n" +
	"\x05usage\x18\x06 \x01(\tR\x05usage\x12\"\n" +
	"\rdev_serial_id\x18\a \x01(\tR\vdevSerialId\x12O\n" +
	"\n" +
	"layer_type\x18\b \x01(\x0e20.cubelet.services.cubebox.hostimage.v1.LayerTypeR\tlayerType\"\xcd\x02\n" +
	"\bImageDev\x12\x1b\n" +
	"\tserial_id\x18\x01 \x01(\tR\bserialId\x12(\n" +
	"\x10host_device_path\x18\x02 \x01(\tR\x0ehostDevicePath\x12$\n" +
	"\x0evm_device_path\x18\x03 \x01(\tR\fvmDevicePath\x12 \n" +
	"\fvm_root_path\x18\x04 \x01(\tR\n" +
	"vmRootPath\x12\x17\n" +
	"\afs_type\x18\x05 \x01(\tR\x06fsType\x12#\n" +
	"\rmount_options\x18\x06 \x03(\tR\fmountOptions\x12\x1c\n" +
	"\tsnapshots\x18\a \x03(\tR\tsnapshots\x12\x19\n" +
	"\bimage_id\x18\b \x01(\tR\aimageId\x12)\n" +
	"\x10image_references\x18\t \x03(\tR\x0fimageReferences\x12\x10\n" +
	"\x03bdf\x18\n" +
	" \x01(\tR\x03bdf\"r\n" +
	"\x12PodSandboxMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\"\xbf\x04\n" +
	"\x10PodSandboxConfig\x12U\n" +
	"\bmetadata\x18\x01 \x01(\v29.cubelet.services.cubebox.hostimage.v1.PodSandboxMetadataR\bmetadata\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12#\n" +
	"\rlog_directory\x18\x03 \x01(\tR\flogDirectory\x12O\n" +
	"\n" +
	"dns_config\x18\x04 \x01(\v20.cubelet.services.cubebox.hostimage.v1.DNSConfigR\tdnsConfig\x12[\n" +
	"\x06labels\x18\x06 \x03(\v2C.cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.LabelsEntryR\x06labels\x12j\n" +
	"\vannotations\x18\a \x03(\v2H.cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\tDNSConfig\x12\x18\n" +
	"\aservers\x18\x01 \x03(\tR\aservers\x12\x1a\n" +
	"\bsearches\x18\x02 \x03(\tR\bsearches\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"l\n" +
	"\x15RemoveSnapshotRequest\x12S\n" +
	"\vLayerMounts\x18\n" +
	" \x03(\v21.cubelet.services.cubebox.hostimage.v1.LayerMountR\vLayerMounts\"i\n" +
	"\x13ListInflightRequest\x12R\n" +
	"\brequests\x18\x01 \x03(\v26.cubelet.services.cubebox.hostimage.v1.InflightRequestR\brequests\"!\n" +
	"\x0fInflightRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x11ListImagesRequest\x122\n" +
	"\x06filter\x18\x01 \x01(\v2\x1a.cubelet.types.ImageFilterR\x06filter\"B\n" +
	"\x12ListImagesResponse\x12,\n" +
	"\x06images\x18\x01 \x03(\v2\x14.cubelet.types.ImageR\x06images\"z\n" +
	"\fImageFsStats\x12&\n" +
	"\x0eAvailableBytes\x18\x01 \x01(\x04R\x0eAvailableBytes\x12$\n" +
	"\rCapacityBytes\x18\x02 \x01(\x04R\rCapacityBytes\x12\x1c\n" +
	"\tUsedBytes\x18\x03 \x01(\x04R\tUsedBytes\"c\n" +
	"\x11MountImageRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg*v\n" +
	"\vMessageType\x12\x10\n" +
	"\fCLIENT_HELLO\x10\x00\x12\x11\n" +
	"\rIMAGE_FORWARD\x10\x01\x12\x13\n" +
	"\x0fREMOVE_SNAPSHOT\x10\x02\x12\x19\n" +
	"\x15LIST_INFLIGHT_REQUEST\x10\x03\x12\x12\n" +
	"\x0eIMAGE_FS_STATS\x10\x04*'\n" +
	"\x12ResponseStatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01*5\n" +
	"\tLayerType\x12\x11\n" +
	"\rLAYER_TYPE_FS\x10\x00\x12\x15\n" +
	"\x11LAYER_TYPE_DEVICE\x10\x012\xa8\x02\n" +
	"\x14CubeHostImageService\x12\x8b\x01\n" +
	"\x19ReverseStreamForwardImage\x124.cubelet.services.cubebox.hostimage.v1.ClientMessage\x1a4.cubelet.services.cubebox.hostimage.v1.ServerMessage(\x010\x01\x12\x81\x01\n" +
	"\n" +
	"ListImages\x128.cubelet.services.cubebox.hostimage.v1.ListImagesRequest\x1a9.cubelet.services.cubebox.hostimage.v1.ListImagesResponse2\x9c\x03\n" +
	"\x12CubeVMImageService\x12\x81\x01\n" +
	"\n" +
	"ListImages\x128.cubelet.services.cubebox.hostimage.v1.ListImagesRequest\x1a9.cubelet.services.cubebox.hostimage.v1.ListImagesResponse\x12\x84\x01\n" +
	"\tPullImage\x12:.cubelet.services.cubebox.hostimage.v1.ForwardImageRequest\x1a;.cubelet.services.cubebox.hostimage.v1.ForwardImageResponse\x12{\n" +
	"\x05Mount\x128.cubelet.services.cubebox.hostimage.v1.MountImageRequest\x1a8.cubelet.services.cubebox.hostimage.v1.MountImageRequestBOZMgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/cubehost/v1;cubehostb\x06proto3"

var (
	file_api_services_cubehost_v1_hostimage_proto_rawDescOnce sync.Once
	file_api_services_cubehost_v1_hostimage_proto_rawDescData []byte
)

func file_api_services_cubehost_v1_hostimage_proto_rawDescGZIP() []byte {
	file_api_services_cubehost_v1_hostimage_proto_rawDescOnce.Do(func() {
		file_api_services_cubehost_v1_hostimage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_cubehost_v1_hostimage_proto_rawDesc), len(file_api_services_cubehost_v1_hostimage_proto_rawDesc)))
	})
	return file_api_services_cubehost_v1_hostimage_proto_rawDescData
}

var file_api_services_cubehost_v1_hostimage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_services_cubehost_v1_hostimage_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_services_cubehost_v1_hostimage_proto_goTypes = []any{
	(MessageType)(0),              // 0: cubelet.services.cubebox.hostimage.v1.MessageType
	(ResponseStatusCode)(0),       // 1: cubelet.services.cubebox.hostimage.v1.ResponseStatusCode
	(LayerType)(0),                // 2: cubelet.services.cubebox.hostimage.v1.LayerType
	(*ClientMessage)(nil),         // 3: cubelet.services.cubebox.hostimage.v1.ClientMessage
	(*ServerMessage)(nil),         // 4: cubelet.services.cubebox.hostimage.v1.ServerMessage
	(*ResponseStatus)(nil),        // 5: cubelet.services.cubebox.hostimage.v1.ResponseStatus
	(*ForwardImageResponse)(nil),  // 6: cubelet.services.cubebox.hostimage.v1.ForwardImageResponse
	(*ForwardImageRequest)(nil),   // 7: cubelet.services.cubebox.hostimage.v1.ForwardImageRequest
	(*HostImage)(nil),             // 8: cubelet.services.cubebox.hostimage.v1.HostImage
	(*LayerMount)(nil),            // 9: cubelet.services.cubebox.hostimage.v1.LayerMount
	(*ImageDev)(nil),              // 10: cubelet.services.cubebox.hostimage.v1.ImageDev
	(*PodSandboxMetadata)(nil),    // 11: cubelet.services.cubebox.hostimage.v1.PodSandboxMetadata
	(*PodSandboxConfig)(nil),      // 12: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig
	(*DNSConfig)(nil),             // 13: cubelet.services.cubebox.hostimage.v1.DNSConfig
	(*RemoveSnapshotRequest)(nil), // 14: cubelet.services.cubebox.hostimage.v1.RemoveSnapshotRequest
	(*ListInflightRequest)(nil),   // 15: cubelet.services.cubebox.hostimage.v1.ListInflightRequest
	(*InflightRequest)(nil),       // 16: cubelet.services.cubebox.hostimage.v1.InflightRequest
	(*ListImagesRequest)(nil),     // 17: cubelet.services.cubebox.hostimage.v1.ListImagesRequest
	(*ListImagesResponse)(nil),    // 18: cubelet.services.cubebox.hostimage.v1.ListImagesResponse
	(*ImageFsStats)(nil),          // 19: cubelet.services.cubebox.hostimage.v1.ImageFsStats
	(*MountImageRequest)(nil),     // 20: cubelet.services.cubebox.hostimage.v1.MountImageRequest
	nil,                           // 21: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.LabelsEntry
	nil,                           // 22: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.AnnotationsEntry
	(*v1.ImageSpec)(nil),          // 23: cubelet.types.ImageSpec
	(*v1.AuthConfig)(nil),         // 24: cubelet.types.AuthConfig
	(*anypb.Any)(nil),             // 25: google.protobuf.Any
	(*v1.ImageFilter)(nil),        // 26: cubelet.types.ImageFilter
	(*v1.Image)(nil),              // 27: cubelet.types.Image
}
var file_api_services_cubehost_v1_hostimage_proto_depIdxs = []int32{
	5,  // 0: cubelet.services.cubebox.hostimage.v1.ClientMessage.status:type_name -> cubelet.services.cubebox.hostimage.v1.ResponseStatus
	0,  // 1: cubelet.services.cubebox.hostimage.v1.ClientMessage.type:type_name -> cubelet.services.cubebox.hostimage.v1.MessageType
	6,  // 2: cubelet.services.cubebox.hostimage.v1.ClientMessage.forwardImageResponse:type_name -> cubelet.services.cubebox.hostimage.v1.ForwardImageResponse
	15, // 3: cubelet.services.cubebox.hostimage.v1.ClientMessage.listInflightRequest:type_name -> cubelet.services.cubebox.hostimage.v1.ListInflightRequest
	19, // 4: cubelet.services.cubebox.hostimage.v1.ClientMessage.imageFsStats:type_name -> cubelet.services.cubebox.hostimage.v1.ImageFsStats
	5,  // 5: cubelet.services.cubebox.hostimage.v1.ServerMessage.status:type_name -> cubelet.services.cubebox.hostimage.v1.ResponseStatus
	0,  // 6: cubelet.services.cubebox.hostimage.v1.ServerMessage.type:type_name -> cubelet.services.cubebox.hostimage.v1.MessageType
	7,  // 7: cubelet.services.cubebox.hostimage.v1.ServerMessage.forwardImageRequest:type_name -> cubelet.services.cubebox.hostimage.v1.ForwardImageRequest
	14, // 8: cubelet.services.cubebox.hostimage.v1.ServerMessage.removeSnapshotRequest:type_name -> cubelet.services.cubebox.hostimage.v1.RemoveSnapshotRequest
	15, // 9: cubelet.services.cubebox.hostimage.v1.ServerMessage.listInflightRequest:type_name -> cubelet.services.cubebox.hostimage.v1.ListInflightRequest
	1,  // 10: cubelet.services.cubebox.hostimage.v1.ResponseStatus.code:type_name -> cubelet.services.cubebox.hostimage.v1.ResponseStatusCode
	8,  // 11: cubelet.services.cubebox.hostimage.v1.ForwardImageResponse.image:type_name -> cubelet.services.cubebox.hostimage.v1.HostImage
	23, // 12: cubelet.services.cubebox.hostimage.v1.ForwardImageRequest.image:type_name -> cubelet.types.ImageSpec
	24, // 13: cubelet.services.cubebox.hostimage.v1.ForwardImageRequest.auth:type_name -> cubelet.types.AuthConfig
	12, // 14: cubelet.services.cubebox.hostimage.v1.ForwardImageRequest.sandbox_config:type_name -> cubelet.services.cubebox.hostimage.v1.PodSandboxConfig
	23, // 15: cubelet.services.cubebox.hostimage.v1.HostImage.spec:type_name -> cubelet.types.ImageSpec
	25, // 16: cubelet.services.cubebox.hostimage.v1.HostImage.descriptors:type_name -> google.protobuf.Any
	9,  // 17: cubelet.services.cubebox.hostimage.v1.HostImage.LayerMounts:type_name -> cubelet.services.cubebox.hostimage.v1.LayerMount
	10, // 18: cubelet.services.cubebox.hostimage.v1.HostImage.image_devs:type_name -> cubelet.services.cubebox.hostimage.v1.ImageDev
	2,  // 19: cubelet.services.cubebox.hostimage.v1.LayerMount.layer_type:type_name -> cubelet.services.cubebox.hostimage.v1.LayerType
	11, // 20: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.metadata:type_name -> cubelet.services.cubebox.hostimage.v1.PodSandboxMetadata
	13, // 21: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.dns_config:type_name -> cubelet.services.cubebox.hostimage.v1.DNSConfig
	21, // 22: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.labels:type_name -> cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.LabelsEntry
	22, // 23: cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.annotations:type_name -> cubelet.services.cubebox.hostimage.v1.PodSandboxConfig.AnnotationsEntry
	9,  // 24: cubelet.services.cubebox.hostimage.v1.RemoveSnapshotRequest.LayerMounts:type_name -> cubelet.services.cubebox.hostimage.v1.LayerMount
	16, // 25: cubelet.services.cubebox.hostimage.v1.ListInflightRequest.requests:type_name -> cubelet.services.cubebox.hostimage.v1.InflightRequest
	26, // 26: cubelet.services.cubebox.hostimage.v1.ListImagesRequest.filter:type_name -> cubelet.types.ImageFilter
	27, // 27: cubelet.services.cubebox.hostimage.v1.ListImagesResponse.images:type_name -> cubelet.types.Image
	3,  // 28: cubelet.services.cubebox.hostimage.v1.CubeHostImageService.ReverseStreamForwardImage:input_type -> cubelet.services.cubebox.hostimage.v1.ClientMessage
	17, // 29: cubelet.services.cubebox.hostimage.v1.CubeHostImageService.ListImages:input_type -> cubelet.services.cubebox.hostimage.v1.ListImagesRequest
	17, // 30: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.ListImages:input_type -> cubelet.services.cubebox.hostimage.v1.ListImagesRequest
	7,  // 31: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.PullImage:input_type -> cubelet.services.cubebox.hostimage.v1.ForwardImageRequest
	20, // 32: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.Mount:input_type -> cubelet.services.cubebox.hostimage.v1.MountImageRequest
	4,  // 33: cubelet.services.cubebox.hostimage.v1.CubeHostImageService.ReverseStreamForwardImage:output_type -> cubelet.services.cubebox.hostimage.v1.ServerMessage
	18, // 34: cubelet.services.cubebox.hostimage.v1.CubeHostImageService.ListImages:output_type -> cubelet.services.cubebox.hostimage.v1.ListImagesResponse
	18, // 35: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.ListImages:output_type -> cubelet.services.cubebox.hostimage.v1.ListImagesResponse
	6,  // 36: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.PullImage:output_type -> cubelet.services.cubebox.hostimage.v1.ForwardImageResponse
	20, // 37: cubelet.services.cubebox.hostimage.v1.CubeVMImageService.Mount:output_type -> cubelet.services.cubebox.hostimage.v1.MountImageRequest
	33, // [33:38] is the sub-list for method output_type
	28, // [28:33] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_services_cubehost_v1_hostimage_proto_init() }
func file_api_services_cubehost_v1_hostimage_proto_init() {
	if File_api_services_cubehost_v1_hostimage_proto != nil {
		return
	}
	file_api_services_cubehost_v1_hostimage_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_ForwardImageResponse)(nil),
		(*ClientMessage_Common)(nil),
		(*ClientMessage_ListInflightRequest)(nil),
		(*ClientMessage_ImageFsStats)(nil),
	}
	file_api_services_cubehost_v1_hostimage_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Hello)(nil),
		(*ServerMessage_ForwardImageRequest)(nil),
		(*ServerMessage_RemoveSnapshotRequest)(nil),
		(*ServerMessage_ListInflightRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_cubehost_v1_hostimage_proto_rawDesc), len(file_api_services_cubehost_v1_hostimage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_services_cubehost_v1_hostimage_proto_goTypes,
		DependencyIndexes: file_api_services_cubehost_v1_hostimage_proto_depIdxs,
		EnumInfos:         file_api_services_cubehost_v1_hostimage_proto_enumTypes,
		MessageInfos:      file_api_services_cubehost_v1_hostimage_proto_msgTypes,
	}.Build()
	File_api_services_cubehost_v1_hostimage_proto = out.File
	file_api_services_cubehost_v1_hostimage_proto_goTypes = nil
	file_api_services_cubehost_v1_hostimage_proto_depIdxs = nil
}
