// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/cubehost/v1/hostimage.proto

package cubehost

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CubeHostImageService_ReverseStreamForwardImage_FullMethodName = "/cubelet.services.cubebox.hostimage.v1.CubeHostImageService/ReverseStreamForwardImage"
	CubeHostImageService_ListImages_FullMethodName                = "/cubelet.services.cubebox.hostimage.v1.CubeHostImageService/ListImages"
)

// CubeHostImageServiceClient is the client API for CubeHostImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CubeHostImageServiceClient interface {
	// ReverseStreamForwardImage Reverse forwarding image download interface:
	//  1. After launching the sandbox, the cubelet on the host first attempts to send a hello message
	//     indicating successful connection. The server inside the VM should establish a context
	//     representing this connection is ready.
	//  2. When the server inside the VM receives a CRI image download request, it should send a reverse
	//     forwardImageRequest to the host to request image download.
	//  3. After completing the image download on the host, it should proactively notify the VM with
	//     the image information based on the request ID.
	//
	// Note: When the host has not actively connected to the server inside the VM,
	// the server is considered invalid and image forwarding is prohibited.
	ReverseStreamForwardImage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// ListImages lists existing images.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
}

type cubeHostImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeHostImageServiceClient(cc grpc.ClientConnInterface) CubeHostImageServiceClient {
	return &cubeHostImageServiceClient{cc}
}

func (c *cubeHostImageServiceClient) ReverseStreamForwardImage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CubeHostImageService_ServiceDesc.Streams[0], CubeHostImageService_ReverseStreamForwardImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CubeHostImageService_ReverseStreamForwardImageClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *cubeHostImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, CubeHostImageService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeHostImageServiceServer is the server API for CubeHostImageService service.
// All implementations must embed UnimplementedCubeHostImageServiceServer
// for forward compatibility.
type CubeHostImageServiceServer interface {
	// ReverseStreamForwardImage Reverse forwarding image download interface:
	//  1. After launching the sandbox, the cubelet on the host first attempts to send a hello message
	//     indicating successful connection. The server inside the VM should establish a context
	//     representing this connection is ready.
	//  2. When the server inside the VM receives a CRI image download request, it should send a reverse
	//     forwardImageRequest to the host to request image download.
	//  3. After completing the image download on the host, it should proactively notify the VM with
	//     the image information based on the request ID.
	//
	// Note: When the host has not actively connected to the server inside the VM,
	// the server is considered invalid and image forwarding is prohibited.
	ReverseStreamForwardImage(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// ListImages lists existing images.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	mustEmbedUnimplementedCubeHostImageServiceServer()
}

// UnimplementedCubeHostImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeHostImageServiceServer struct{}

func (UnimplementedCubeHostImageServiceServer) ReverseStreamForwardImage(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method ReverseStreamForwardImage not implemented")
}
func (UnimplementedCubeHostImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedCubeHostImageServiceServer) mustEmbedUnimplementedCubeHostImageServiceServer() {}
func (UnimplementedCubeHostImageServiceServer) testEmbeddedByValue()                              {}

// UnsafeCubeHostImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeHostImageServiceServer will
// result in compilation errors.
type UnsafeCubeHostImageServiceServer interface {
	mustEmbedUnimplementedCubeHostImageServiceServer()
}

func RegisterCubeHostImageServiceServer(s grpc.ServiceRegistrar, srv CubeHostImageServiceServer) {
	// If the following call panics, it indicates UnimplementedCubeHostImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeHostImageService_ServiceDesc, srv)
}

func _CubeHostImageService_ReverseStreamForwardImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CubeHostImageServiceServer).ReverseStreamForwardImage(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CubeHostImageService_ReverseStreamForwardImageServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _CubeHostImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeHostImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeHostImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeHostImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeHostImageService_ServiceDesc is the grpc.ServiceDesc for CubeHostImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeHostImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.hostimage.v1.CubeHostImageService",
	HandlerType: (*CubeHostImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _CubeHostImageService_ListImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReverseStreamForwardImage",
			Handler:       _CubeHostImageService_ReverseStreamForwardImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/services/cubehost/v1/hostimage.proto",
}

const (
	CubeVMImageService_ListImages_FullMethodName = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/ListImages"
	CubeVMImageService_PullImage_FullMethodName  = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/PullImage"
	CubeVMImageService_Mount_FullMethodName      = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/Mount"
)

// CubeVMImageServiceClient is the client API for CubeVMImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CubeVMImageService is used by cube image converter service in vm.
type CubeVMImageServiceClient interface {
	// ListImages lists existing images.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// PullImage pulls an image from the host.
	PullImage(ctx context.Context, in *ForwardImageRequest, opts ...grpc.CallOption) (*ForwardImageResponse, error)
	// mount image to target path
	Mount(ctx context.Context, in *MountImageRequest, opts ...grpc.CallOption) (*MountImageRequest, error)
}

type cubeVMImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeVMImageServiceClient(cc grpc.ClientConnInterface) CubeVMImageServiceClient {
	return &cubeVMImageServiceClient{cc}
}

func (c *cubeVMImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, CubeVMImageService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeVMImageServiceClient) PullImage(ctx context.Context, in *ForwardImageRequest, opts ...grpc.CallOption) (*ForwardImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardImageResponse)
	err := c.cc.Invoke(ctx, CubeVMImageService_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeVMImageServiceClient) Mount(ctx context.Context, in *MountImageRequest, opts ...grpc.CallOption) (*MountImageRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountImageRequest)
	err := c.cc.Invoke(ctx, CubeVMImageService_Mount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeVMImageServiceServer is the server API for CubeVMImageService service.
// All implementations must embed UnimplementedCubeVMImageServiceServer
// for forward compatibility.
//
// CubeVMImageService is used by cube image converter service in vm.
type CubeVMImageServiceServer interface {
	// ListImages lists existing images.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// PullImage pulls an image from the host.
	PullImage(context.Context, *ForwardImageRequest) (*ForwardImageResponse, error)
	// mount image to target path
	Mount(context.Context, *MountImageRequest) (*MountImageRequest, error)
	mustEmbedUnimplementedCubeVMImageServiceServer()
}

// UnimplementedCubeVMImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeVMImageServiceServer struct{}

func (UnimplementedCubeVMImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedCubeVMImageServiceServer) PullImage(context.Context, *ForwardImageRequest) (*ForwardImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedCubeVMImageServiceServer) Mount(context.Context, *MountImageRequest) (*MountImageRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedCubeVMImageServiceServer) mustEmbedUnimplementedCubeVMImageServiceServer() {}
func (UnimplementedCubeVMImageServiceServer) testEmbeddedByValue()                            {}

// UnsafeCubeVMImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeVMImageServiceServer will
// result in compilation errors.
type UnsafeCubeVMImageServiceServer interface {
	mustEmbedUnimplementedCubeVMImageServiceServer()
}

func RegisterCubeVMImageServiceServer(s grpc.ServiceRegistrar, srv CubeVMImageServiceServer) {
	// If the following call panics, it indicates UnimplementedCubeVMImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeVMImageService_ServiceDesc, srv)
}

func _CubeVMImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeVMImageService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).PullImage(ctx, req.(*ForwardImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeVMImageService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).Mount(ctx, req.(*MountImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeVMImageService_ServiceDesc is the grpc.ServiceDesc for CubeVMImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeVMImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.hostimage.v1.CubeVMImageService",
	HandlerType: (*CubeVMImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _CubeVMImageService_ListImages_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _CubeVMImageService_PullImage_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _CubeVMImageService_Mount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/cubehost/v1/hostimage.proto",
}
